# Generated by Django 5.1.1 on 2024-09-15 06:14

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("courses", "0002_category_course_price_enrollment_enrolled_on"),
    ]

    operations = [
        migrations.AlterField(
            model_name="enrollment",
            name="enrolled_on",
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
