# Generated by Django 5.1.1 on 2024-09-20 19:53

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("courses", "0004_event_knowledgebasearticle_review_service_teacher_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="ContactMessage",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100)),
                ("email", models.EmailField(max_length=254)),
                ("message", models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name="FAQ",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("question", models.CharField(max_length=255)),
                ("answer", models.TextField()),
            ],
        ),
        migrations.AddField(
            model_name="event",
            name="image",
            field=models.ImageField(blank=True, null=True, upload_to="events/"),
        ),
        migrations.AddField(
            model_name="knowledgebasearticle",
            name="level",
            field=models.CharField(default="Beginner", max_length=50),
        ),
        migrations.AddField(
            model_name="review",
            name="video_url",
            field=models.URLField(blank=True, null=True),
        ),
    ]
