# Generated by Django 5.1.1 on 2024-09-28 09:44

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("courses", "0005_contactmessage_faq_event_image_and_more"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name="contactmessage",
            name="phone_number",
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AddField(
            model_name="course",
            name="end_date",
            field=models.DateField(
                blank=True, help_text="Дата окончания курса", null=True
            ),
        ),
        migrations.AddField(
            model_name="course",
            name="level",
            field=models.CharField(
                choices=[
                    ("beginner", "Beginner"),
                    ("intermediate", "Intermediate"),
                    ("advanced", "Advanced"),
                ],
                default="beginner",
                help_text="Уровень курса",
                max_length=20,
            ),
        ),
        migrations.AddField(
            model_name="course",
            name="requirements",
            field=models.TextField(
                blank=True, help_text="Требования к слушателям", null=True
            ),
        ),
        migrations.AddField(
            model_name="course",
            name="start_date",
            field=models.DateField(
                blank=True, help_text="Дата начала курса", null=True
            ),
        ),
        migrations.AddField(
            model_name="course",
            name="syllabus",
            field=models.TextField(blank=True, help_text="Программа курса", null=True),
        ),
        migrations.AddField(
            model_name="review",
            name="course",
            field=models.ForeignKey(
                default=1,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="reviews",
                to="courses.course",
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="teacher",
            name="email",
            field=models.EmailField(blank=True, max_length=254, null=True),
        ),
        migrations.AddField(
            model_name="teacher",
            name="linkedin_url",
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="teacher",
            name="phone_number",
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.CreateModel(
            name="Payment",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("amount", models.DecimalField(decimal_places=2, max_digits=10)),
                ("stripe_payment_intent", models.CharField(max_length=200)),
                ("timestamp", models.DateTimeField(auto_now_add=True)),
                ("status", models.CharField(default="pending", max_length=20)),
                (
                    "course",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="courses.course"
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
    ]
