# Generated by Django 5.1.1 on 2024-09-29 11:20

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("courses", "0006_contactmessage_phone_number_course_end_date_and_more"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="course",
            options={"ordering": ["id"]},
        ),
    ]
