# Generated by Django 5.1.1 on 2024-10-01 00:38

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("courses", "0007_alter_course_options"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name="contactmessage",
            name="received_at",
            field=models.DateTimeField(
                auto_now_add=True, default=django.utils.timezone.now
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="course",
            name="is_popular",
            field=models.BooleanField(default=False, help_text="Популярный курс"),
        ),
        migrations.AddField(
            model_name="course",
            name="language",
            field=models.CharField(
                default="English", help_text="Язык курса", max_length=50
            ),
        ),
        migrations.AddField(
            model_name="course",
            name="type",
            field=models.CharField(
                choices=[
                    ("grammar", "Grammar"),
                    ("conversation", "Conversation"),
                    ("exam_preparation", "Exam Preparation"),
                    ("business", "Business English"),
                ],
                default="conversation",
                help_text="Тип курса",
                max_length=50,
            ),
        ),
        migrations.AddField(
            model_name="enrollment",
            name="completion_date",
            field=models.DateField(
                blank=True, help_text="Дата завершения курса", null=True
            ),
        ),
        migrations.AddField(
            model_name="event",
            name="location",
            field=models.CharField(
                blank=True, help_text="Место проведения", max_length=200, null=True
            ),
        ),
        migrations.AddField(
            model_name="faq",
            name="category",
            field=models.CharField(
                blank=True, help_text="Категория FAQ", max_length=100, null=True
            ),
        ),
        migrations.AddField(
            model_name="knowledgebasearticle",
            name="is_featured",
            field=models.BooleanField(default=False, help_text="Выделенная статья"),
        ),
        migrations.AddField(
            model_name="review",
            name="rating",
            field=models.IntegerField(default=5, help_text="Рейтинг от 1 до 5"),
        ),
        migrations.AddField(
            model_name="teacher",
            name="expertise",
            field=models.CharField(
                blank=True, help_text="Область знаний", max_length=200, null=True
            ),
        ),
        migrations.AlterField(
            model_name="course",
            name="instructor",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="courses",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AlterField(
            model_name="enrollment",
            name="status",
            field=models.CharField(
                choices=[
                    ("pending", "Pending"),
                    ("confirmed", "Confirmed"),
                    ("cancelled", "Cancelled"),
                ],
                default="pending",
                max_length=20,
            ),
        ),
        migrations.CreateModel(
            name="BlogPost",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=200)),
                ("content", models.TextField()),
                ("image", models.ImageField(upload_to="blog_images/")),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "tags",
                    models.CharField(
                        blank=True,
                        help_text="Теги, разделенные запятыми",
                        max_length=100,
                        null=True,
                    ),
                ),
                (
                    "author",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Profile",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "bio",
                    models.TextField(
                        blank=True, help_text="Биография пользователя", null=True
                    ),
                ),
                (
                    "avatar",
                    models.ImageField(
                        blank=True,
                        help_text="Фото профиля",
                        null=True,
                        upload_to="profiles/",
                    ),
                ),
                (
                    "phone_number",
                    models.CharField(blank=True, max_length=20, null=True),
                ),
                ("location", models.CharField(blank=True, max_length=100, null=True)),
                (
                    "user",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="profile",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Testimonial",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100)),
                ("content", models.TextField()),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "rating",
                    models.IntegerField(default=5, help_text="Рейтинг от 1 до 5"),
                ),
                (
                    "course",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="courses.course"
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Certificate",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("issued_on", models.DateTimeField(auto_now_add=True)),
                (
                    "certificate_url",
                    models.URLField(blank=True, help_text="URL сертификата", null=True),
                ),
                (
                    "verified",
                    models.BooleanField(
                        default=False, help_text="Сертификат проверен и действителен"
                    ),
                ),
                (
                    "course",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="certificates",
                        to="courses.course",
                    ),
                ),
                (
                    "student",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="certificates",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "unique_together": {("student", "course")},
            },
        ),
        migrations.CreateModel(
            name="CourseProgress",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "completed_lessons",
                    models.IntegerField(
                        default=0, help_text="Количество завершенных уроков"
                    ),
                ),
                (
                    "total_lessons",
                    models.IntegerField(default=0, help_text="Общее количество уроков"),
                ),
                (
                    "progress",
                    models.FloatField(
                        default=0.0, help_text="Процент завершения курса"
                    ),
                ),
                (
                    "is_completed",
                    models.BooleanField(default=False, help_text="Курс завершен"),
                ),
                (
                    "course",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="progress",
                        to="courses.course",
                    ),
                ),
                (
                    "student",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="progress",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "unique_together": {("student", "course")},
            },
        ),
    ]
